// docs/src/components/vue/core/navigation/NavBar.vue
<template>
  <header class="sticky top-0 z-50 w-full border-b border-surface-lighter bg-background-dark/80 backdrop-blur-md">
    <div class="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
      <!-- Logo -->
      <a
        class="flex items-center gap-2 text-white group focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/70 rounded-lg"
        href="/"
      >
        <div class="flex size-8 items-center justify-center rounded-lg bg-primary/20 text-primary transition-all group-hover:shadow-[0_0_15px_rgba(166,13,242,0.5)]">
          <TicketIcon
            aria-hidden="true"
            class="w-5 h-5"
          />
        </div>
        <h2 class="font-display text-lg font-bold tracking-tight">Open Ticket AI</h2>
      </a>

      <!-- Desktop Navigation -->
      <nav class="hidden md:flex flex-1 justify-center gap-8 text-sm font-medium">
        <a
          v-for="item in navItems"
          :key="item.href"
          :aria-current="isActive(item.href) ? 'page' : undefined"
          :class="isActive(item.href) ? 'text-white' : 'text-gray-400 hover:text-white'"
          :href="item.href"
          class="transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60 rounded-lg px-2 py-1"
        >
          {{ item.label }}
        </a>
      </nav>

      <!-- Desktop Primary Button -->
      <div class="hidden md:flex items-center">
        <Button
          variant="primary"
          size="sm"
        >
          {{ ctaLabel }}
        </Button>
      </div>

      <!-- Mobile Menu Button -->
      <button
        class="md:hidden flex items-center justify-center p-2 text-gray-400 hover:text-white transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60 rounded-lg"
        aria-label="Open menu"
        @click="openMobileMenu"
      >
        <Bars3Icon class="h-6 w-6" />
      </button>
    </div>

    <!-- Mobile Menu Dialog -->
    <TransitionRoot
      :show="mobileMenuOpen"
      as="template"
    >
      <Dialog
        class="relative z-50 md:hidden"
        @close="closeMobileMenu"
      >
        <UiTransitionFade>
          <div class="fixed inset-0 bg-black/80 backdrop-blur-sm" />
        </UiTransitionFade>

        <div class="fixed inset-0 flex items-start justify-end">
          <UiTransitionSlide direction="right">
            <DialogPanel class="w-full max-w-sm h-full bg-background-dark border-l border-surface-lighter p-6 shadow-2xl">
              <div class="flex items-center justify-between mb-8">
                <DialogTitle class="text-lg font-bold text-white">
                  Menu
                </DialogTitle>
                <button
                  class="p-2 text-gray-400 hover:text-white transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60 rounded-lg"
                  aria-label="Close menu"
                  @click="closeMobileMenu"
                >
                  <XMarkIcon class="h-6 w-6" />
                </button>
              </div>

              <nav class="flex flex-col gap-4">
                <a
                  v-for="item in navItems"
                  :key="item.href"
                  :href="item.href"
                  :class="[
                    'px-4 py-3 rounded-xl text-base font-medium transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60',
                    isActive(item.href) 
                      ? 'bg-primary/20 text-white border border-primary/40' 
                      : 'text-gray-400 hover:text-white hover:bg-surface-lighter'
                  ]"
                  @click="closeMobileMenu"
                >
                  {{ item.label }}
                </a>

                <div class="mt-6 pt-6 border-t border-surface-lighter">
                  <Button
                    variant="primary"
                    size="md"
                    class="w-full"
                  >
                    {{ ctaLabel }}
                  </Button>
                </div>
              </nav>
            </DialogPanel>
          </UiTransitionSlide>
        </div>
      </Dialog>
    </TransitionRoot>
  </header>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue'
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  TransitionRoot
} from '@headlessui/vue'
import {
  TicketIcon,
  Bars3Icon,
  XMarkIcon
} from '@heroicons/vue/24/outline'
import Button from '../basic/Button.vue'
import UiTransitionFade from '../transitions/UiTransitionFade.vue'
import UiTransitionSlide from '../transitions/UiTransitionSlide.vue'

type NavItem = { href: string; label: string }

type Props = {
  navItems?: NavItem[]
  currentPath?: string
  ctaLabel?: string
}

const props = defineProps<Props>()

const defaultNavItems: NavItem[] = [
  { href: '/products/', label: 'Products' },
  { href: '/services/', label: 'Services' },
  { href: '/pricing/', label: 'Pricing' },
  { href: '/docs/', label: 'Docs' }
]

const navItems = computed(() => props.navItems ?? defaultNavItems)
const ctaLabel = computed(() => props.ctaLabel ?? 'Get Started')

const activePath = ref(props.currentPath ?? '/')
const updateActivePath = () => {
  if (typeof window !== 'undefined') {
    activePath.value = props.currentPath ?? window.location.pathname
  }
}

onMounted(() => {
  updateActivePath()
})

const mobileMenuOpen = ref(false)
const openMobileMenu = () => {
  mobileMenuOpen.value = true
}
const closeMobileMenu = () => {
  mobileMenuOpen.value = false
}

const isActive = (href: string) => activePath.value === href || activePath.value.startsWith(href)
</script>

// docs/open-ticket-ai-platform-prototype/components/Navbar.tsx

import React from 'react';
import { Link, useLocation } from 'react-router-dom';

const Navbar: React.FC = () => {
  const location = useLocation();
  const isActive = (path: string) => location.pathname === path;

  return (
    <header className="sticky top-0 z-50 w-full border-b border-surface-lighter bg-background-dark/80 backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <Link to="/" className="flex items-center gap-2 text-white group">
          <div className="flex size-8 items-center justify-center rounded-lg bg-primary/20 text-primary transition-all group-hover:shadow-[0_0_15px_rgba(166,13,242,0.5)]">
            <span className="material-symbols-outlined text-2xl">confirmation_number</span>
          </div>
          <h2 className="font-display text-lg font-bold tracking-tight">Open Ticket AI</h2>
        </Link>
        <nav className="hidden md:flex flex-1 justify-center gap-6">
          <Link to="/products" className={`text-sm font-medium transition-colors ${isActive('/products') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>Products</Link>
          <Link to="/services" className={`text-sm font-medium transition-colors ${isActive('/services') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>Services</Link>
          <Link to="/media-lab" className={`text-sm font-medium transition-colors ${isActive('/media-lab') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>Media Lab</Link>
          <Link to="/docs/ota" className={`text-sm font-medium transition-colors ${isActive('/docs/ota') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>OTA Docs</Link>
          <Link to="/blog" className={`text-sm font-medium transition-colors ${isActive('/blog') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>Blog</Link>
          <Link to="/docs" className={`text-sm font-medium transition-colors ${isActive('/docs') ? 'text-white' : 'text-gray-400 hover:text-white'}`}>Docs Hub</Link>
        </nav>
        <div className="flex items-center gap-4">
          <button className="hidden sm:flex h-9 items-center justify-center rounded-lg bg-surface-lighter px-4 text-sm font-bold text-white transition-colors hover:bg-surface-lighter/80 border border-primary/20">
            Login
          </button>
          <button className="flex h-9 items-center justify-center rounded-lg bg-primary px-4 text-sm font-bold text-white shadow-[0_0_15px_rgba(166,13,242,0.3)] transition-all hover:bg-primary-dark">
            Get Demo
          </button>
        </div>
      </div>
    </header>
  );
};

export default Navbar;
